apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx
 strategy:
   type: RollingUpdate
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - image: <SWR_REGISTRY>/<SWR_ORGANIZATION>/<DOCKER_IMAGENAME_TAG>
       imagePullPolicy: Always
       name: nginx